backend:
  name: git-gateway
  branch: cms # or main, depending on your Git workflow

media_folder: "images/uploads" # where uploaded media will be stored
public_folder: "/images/uploads" # public URL for uploaded media

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }
